config/routes.rb
Rails.application.routes.draw do
  resources :searches
  root to: 'high_voltage/pages#show', id: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  def index
    @searches = Search.all
  end

  # GET /searches/1
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  def create
    @search = Search.new(search_params)

    if @search.save
      redirect_to @search, notice: 'Search was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /searches/1
  def update
    if @search.update(search_params)
      redirect_to @search, notice: 'Search was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /searches/1
  def destroy
    @search.destroy
    redirect_to searches_url, notice: 'Search was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def search_params
      params.fetch(:search, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row expanded callout secondary">

    <div class="small-6 large-3 columns">
      <p class="lead">Links</p>
      <ul class="menu vertical">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/disclosure">Disclosure</a></li>
        <li><a href="/terms_of_use">Terms of Use</a></li>
      </ul>
    </div>

    <div class="small-6 large-3 columns">
      <p>&nbsp;&nbsp;</p>
<!--       <p class="lead">Solar Systems</p>
      <ul class="menu vertical">
        <li><a href="#">One</a></li>
        <li><a href="#">Two</a></li>
        <li><a href="#">Three</a></li>
        <li><a href="#">Four</a></li>
      </ul>
 -->    </div>

    <div class="small-6 large-3 columns">
      <p class="lead">Contact</p>
      <ul class="menu vertical">
        <li><a href="https://twitter.com/wdwhub" target="_blank"><i class="fi-social-twitter"></i> Twitter</a></li>
        <li><a href="https://www.facebook.com/wdwhub/" target="_blank"><i class="fi-social-facebook"></i> Facebook</a></li>
      </ul>
    </div>

    <div class="small-6 large-3 columns">
  <!--     <p class="lead">Offices</p>
      <ul class="menu vertical">
        <li><a href="#">One</a></li>
        <li><a href="#">Two</a></li>
        <li><a href="#">Three</a></li>
        <li><a href="#">Four</a></li>
      </ul>
   -->  </div>

  </div>
  <div class="row">
    <div class="small-12 large-12 columns">
      <%= render :partial => "/layouts/legal_disclosure" %>
    </div>
  </div>
<!--     <div class="medium-6 columns">
      <ul class="menu">
        <li><a href="/pages/disclosure">Legal</a></li>
        <li><a href="#">Partner</a></li>
        <li><a href="#">Explore</a></li>
      </ul>
    </div>

    <div class="medium-6 columns">
      <ul class="menu float-right">
        <li class="menu-text">Copyright</li>
      </ul>
    </div>
 -->  </div>

</footer>

app/views/layouts/_legal_disclosure.html.erb
<div class="row">
	<p class="copyright">&copy; 2017 - WDW Hub and Second Star Labs | WDW Radio is in no way part of, endorsed or authorized by, or affiliated with the Walt Disney Company or its affiliates. As to Disney artwork/properties: &copy; Disney and/or their authors - <a href="/disclosure">Disclosure</a>.</p>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<div class="title-bar" data-responsive-toggle="realEstateMenu" data-hide-for="small">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="realEstateMenu">
  <div class="top-bar-left">
    <ul class="menu" data-responsive-menu="accordion">
      <li class="menu-text">WDW Hub</li>
      <li><a href="/">Home</a></li>
      <li><a href="http://hotels.wdwhub.net">Hotels</a></li>
      <li><a href="http://dining.wdwhub.net">Food</a></li>
      <li><a href="http://fun.wdwhub.net">Fun</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
<!--       <li><a href="#">My Account</a></li>
      <li><a class="button">Login</a></li>
 -->    </ul>
  </div>
</div>
<!-- /Navigation -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "WDW Hub" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => "/layouts/navigation" %>
    <%= yield %>

    <%= render :partial => "/layouts/footer" %>

  </body>
</html>

app/views/pages/_cards.html.erb
<div class="row column">
  <p class="lead">Imagine the place, food and fun!</p>
</div>

<div class="row small-up-1 medium-up-2 large-up-3">
  <div class="column">
    <div class="callout">
      <p><%= link_to "Walt Disney World Hotels", "http://hotels.wdwhub.net" %> </p>
      <p><%= link_to (image_tag "DisneysArtofAnimationResort-RidetheColorWave.jpg", :title => "image of a Walt Disney World Hotel"), "http://hotels.wdwhub.net" %></p>
      <p class="lead">Where can we stay?</p>
      <p class="subheader">With photos, tips, and a map, you are sure to find hotel to fit your needs.</p>
    </div>
  </div>
  <div class="column">
    <div class="callout">
      <p><%= link_to "Walt Disney World Dining", "http://dining.wdwhub.net/" %> </p>
      <p><%= link_to (image_tag "2160747261_741feae5d6_z.jpg", :title => "Walt Disney World Dining"), "http://dining.wdwhub.net/" %></p>
      <p class="lead">What's to eat?</p>
      <p class="subheader">All of the food is good, but some of it is awesome!  Let's find what you like.</p>
    </div>
  </div>

  <div class="column">
    <div class="callout">
      <p><%= link_to "Disney Parks, Shows, and Fun", "http://fun.wdwhub.net" %> </p>
      <p><%= link_to (image_tag "4601302443_904025c08d_z.jpg", :title => "Disney Parks"), "http://fun.wdwhub.net" %></p>
      <p class="lead">Where's the fun?</p>
      <p class="subheader">They're the best in the world.  We will help you scout them out.</p>
    </div>
  </div>

</div>

app/views/pages/_hero.html.erb
<div class="hero">
  <div class="hero-content glass">
      <h1 id="wdw_hub">WDW Hub</h1>
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo Image" class="hero-logo">
    <p>We connect with fans of Walt Disney World across the the web to help you plan and enjoy one of the happiest places on earth.</p>
    
  </div>
</div>

app/views/pages/about.html.erb
<h1 id="home_page">About WDW Hub</h1>

<p>WDW Hub is a collection of websites for the those whom want to connect to the best information on the 'Net about Walt Disney World and the WDW Lifestyle.  It's also the the brainchild of the team at Second Star Labs.  </p>

app/views/pages/disclosure.html.erb
<h1>Disclosure</h1>

<p>This web site is, in part, sponsored or supported by advertisers and sponsors. Any compensation received does not influence the advertising content, topics or posts made on this site, in the podcast, blog and/or videos. That content, advertising space or post may not always be identified as paid or sponsored content.</p>
<p>Even though the owner of this site may receive compensation for advertisements, we always give our honest opinions, findings, beliefs, or experiences on those topics or products. The views and opinions expressed on this site are purely the writer&#8217;s own. Theme park admission, accommodations, dining, experiences and/or special events are generally paid for by the authors/owner of this site at full price unless otherwise indicated. All opinions are entirely those of the authors.</p>
<p>This site may have a marketing connection to a brand, topic or product herein.  Through the use of affiliate links contained herein, the site owner may collect fees  from purchases made.</p>
	

app/views/pages/home.html.erb
<div class="row">

  <div class="medium-7 large-6 columns">
    <h1>WDW Hub</h1>
    <p class="subheader">We connect with fans of Walt Disney World across the the web to help you plan and enjoy one of the happiest places on earth.</p>
    <!-- <button class="button">Take a Tour</button> -->
    <!-- <button class="button">Start a free trial</button> -->
  </div>

  <div class="show-for-large large-3 columns">
    <%= image_tag "32462536921_6cd170a0a6_m.jpg", alt: "cinderella's castle", size:"400x370"%>
    <!-- credit: Chad Sparkes on Flickr, original photo page: https://www.flickr.com/photos/chad_sparkes/32462536921/in/photolist-RsAZfr-Wj4cEC-4FfUVM-XX5W2z-X3Xdgy-6i2Wsy-dRt9ky-j4gE6a-RTsxT5-fnN9mF-X3Xcyb-X4KFdF-VMw48U-b7SoHg-9jtPLb-4Fm3gh-j4y2Qc-VMw4Yb-Ws62MJ-fnNpND-7KRsEZ-4FgMFD-dRnqGH-nqDnjK-X4KEWD-4GKgmm-4Fm2q5-nqD2iV-nqDdyb-fnNe58-7KRsNT-nqD5Wg-5KiyLK-4FgN6Z-7KVrcj-b7h5KB-j4hmCJ-qDJaH9-7KRsLa-gTgGG-j4hmX1-kChZkM-ppkhDZ-6fzAQ-fdP4Gv-4Zz2pz-yxGynS-ofhBPB-nH6Yj3-vCNQR2 -->
  </div>

  <div class="medium-5 large-3 columns">
  	    <%= image_tag "2333878420_2e278d4f26_m.jpg", alt: "cinderella's castle", size:"400x370"%>
		<!-- credit:  Basharat Alam Shah on Flickr, https://www.flickr.com/photos/shahbasharat/2333878420/in/photolist-4yeJK7-6NZrjL-64wCD5-6NZqXw-6NZqKY-6XcUfv-q1t7xJ-4PkoKw-4Pgb6D-4Pg6La-4P5Hwf-4P1qHe-4P5LX1-4P5MBb-SgbVNW-64sjER-64wDmf-TmiviP-s5khjQ-4KcqF6-4EKGYs-4XP1Tz-s7yYgR-s7yYye-s7yYFi-4jf68P-SiQ4jF-4P1Lnz-64sqVF-SXJ7H5-64snfx-64wNF5-64svq2-64so78-64wMoY-64stFz-rPYgG6-rN6wpi-s58yZh-rPYf9M-64stc8-64subi-64sk8p-64wNWU-64skSP-4XP3FH-4P5KCh-4P1LSP-4P5NJy-4KgEV5 -->
<!--      <div class="callout secondary">
      <form action="https://www.google.com/search" method="get">
      	<%# https://www.google.com/search?q=site%3Awdwhub.net+food&ie=utf-8&oe=utf-8 %>
        <div class="row">
          <div class="small-12 columns">
            <label>Find Disneyworld Favorites
              <input name="q" id="q" type="text" placeholder="Search for food and fun">
              <input type="hidden" name="ie" value="utf-8">
              <input type="hidden" name="oe" value="utf-8">
            </label>
          </div>
          <div class="small-12 columns">
            <button type="submit" class="button">Search Now!</button>
          </div>
        </div>
      </form>
    </div>
 -->  </div>

</div>


<%#= render 'pages/hero' %>

<%= render  'pages/cards' %>

app/views/searches/_form.html.erb
<%= simple_form_for(@search) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>